#Implementation
#DB name = ecommerce

#DROP SCHEMA IF EXISTS
DROP TABLE IF EXISTS Carts;
DROP TABLE IF EXISTS Users; 
DROP TABLE IF EXISTS Products;


CREATE TABLE Users(
Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Username VARCHAR(50) NOT NULL,
Password VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL, 
Role VARCHAR(10) DEFAULT "User"
)
ENGINE=InnoDB;


CREATE TABLE Products(
Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ProductName VARCHAR(30) NOT NULL,
Price INT NOT NULL,
Image VARCHAR(100) 
)
ENGINE=InnoDB;

CREATE TABLE Carts(
Id INT NOT NULL AUTO_INCREMENT,
ProductId INT NOT NULL,
Quantity INT NOT NULL,
OrderDate DATE NOT NULL, 
UserId INT NOT NULL,
PRIMARY KEY(Id, ProductId),
CONSTRAINT FK_Products FOREIGN KEY(ProductId) REFERENCES Products(Id),
CONSTRAINT FK_Users FOREIGN KEY(UserId) REFERENCES Users(Id)
)
ENGINE=InnoDB;